
const companies={QH:"Quokka Holdings",II:"Ironbark Industries",BZ:"Blue Zenith Technologies"};
const decks={1:[
{title:"Strong Consumer Spending",text:"Families are spending more money in shops.",impact:{QH:1,II:0,BZ:0}},
{title:"Positive Economic News",text:"Businesses are optimistic about the economy.",impact:{QH:1,II:1,BZ:1}},
{title:"New Infrastructure Contract",text:"A major construction project has been announced.",impact:{QH:0,II:2,BZ:0}},
{title:"Technology Award",text:"A new innovation has attracted attention.",impact:{QH:0,II:0,BZ:2}},
{title:"Rising Business Costs",text:"Higher operating costs affect many companies.",impact:{QH:-1,II:-1,BZ:-1}},
{title:"Online Shopping Boom",text:"Consumer spending continues to grow.",impact:{QH:1,II:0,BZ:1}},
{title:"Investor Confidence Rises",text:"Investors are willing to take more risks.",impact:{QH:1,II:1,BZ:2}},
{title:"Supply Chain Delays",text:"Shipping delays affect some businesses.",impact:{QH:-1,II:-2,BZ:0}},
{title:"New Government Investment",text:"Government spending supports business growth.",impact:{QH:1,II:2,BZ:1}},
{title:"Strong Market Finish",text:"The market closes the lesson positively.",impact:{QH:1,II:1,BZ:1}}],
2:[
{title:"Mixed Trading Day",text:"Some investors take profits while others continue buying.",impact:{QH:1,II:0,BZ:1}},
{title:"Strong Employment Data",text:"The economy appears healthy.",impact:{QH:1,II:1,BZ:2}},
{title:"Overseas Markets Fall",text:"International markets experience losses.",impact:{QH:-1,II:-1,BZ:-2}},
{title:"Investor Uncertainty",text:"Rumours create concern among investors.",impact:{QH:-1,II:-2,BZ:-2}},
{title:"MARKET CRASH",text:"Breaking news shocks investors. Panic selling begins across the market.",impact:{QH:-3,II:-4,BZ:-6}},
{title:"Market Panic Continues",text:"Many investors continue selling.",impact:{QH:-1,II:-2,BZ:-3}},
{title:"Bargain Hunters Enter",text:"Some investors begin buying cheap shares.",impact:{QH:1,II:1,BZ:2}},
{title:"Government Support Package",text:"Confidence begins returning.",impact:{QH:2,II:2,BZ:2}},
{title:"Investor Confidence Returns",text:"The market begins recovering.",impact:{QH:1,II:2,BZ:3}},
{title:"Recovery Rally",text:"Investors return to the market.",impact:{QH:2,II:2,BZ:4}}],
3:[
{title:"Consumer Confidence Returns",text:"Shoppers are spending again.",impact:{QH:2,II:1,BZ:1}},
{title:"Stable Trading Day",text:"Investors remain cautious but optimistic.",impact:{QH:1,II:1,BZ:1}},
{title:"Major Infrastructure Project",text:"Government announces new transport funding.",impact:{QH:0,II:3,BZ:1}},
{title:"Technology Product Launch",text:"A new product receives positive reviews.",impact:{QH:0,II:0,BZ:3}},
{title:"Rising Interest Rates",text:"Borrowing becomes more expensive.",impact:{QH:-1,II:-1,BZ:-2}},
{title:"Strong Company Earnings",text:"Businesses report better-than-expected profits.",impact:{QH:1,II:2,BZ:2}},
{title:"Supply Problems Return",text:"Some industries experience delays.",impact:{QH:-1,II:-2,BZ:-1}},
{title:"Investor Optimism",text:"Many investors expect future growth.",impact:{QH:1,II:1,BZ:2}},
{title:"Market Rally",text:"Investors buy shares across the market.",impact:{QH:2,II:2,BZ:2}},
{title:"End-of-Simulation Surge",text:"Strong buying pushes prices higher before trading closes.",impact:{QH:1,II:2,BZ:3}}]};
const defaultState={prices:{QH:3,II:5,BZ:10},lastChange:{QH:0,II:0,BZ:0},sharesAvailable:{QH:40,II:25,BZ:15},rewards:[8,10,12,15,20,25],students:[],history:[],log:[],lesson:1,deckOrder:{1:[],2:[],3:[]},drawnCounts:{1:0,2:0,3:0},drawnCards:[]};
let state=loadState();
function loadState(){const raw=localStorage.getItem("investorChallengeState");if(raw){try{return JSON.parse(raw)}catch(e){}}const s=JSON.parse(JSON.stringify(defaultState));[1,2,3].forEach(l=>s.deckOrder[l]=[...Array(decks[l].length).keys()]);return s}
function save(){localStorage.setItem("investorChallengeState",JSON.stringify(state))}
function total(st){return Math.round(st.cash+st.bank.reduce((a,d)=>a+d.value,0)+st.QH*state.prices.QH+st.II*state.prices.II+st.BZ*state.prices.BZ)}
function addLog(m){state.log.unshift(`${new Date().toLocaleString()}: ${m}`);state.log=state.log.slice(0,200)}
function cls(v){return v>0?"up":v<0?"down":"flat"} function sig(v){return v>0?`+${v}`:`${v}`}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function snapshot(label){state.students.forEach(st=>state.history.push({round:label,name:st.name,cash:st.cash,bank:st.bank.reduce((a,d)=>a+d.value,0),qh:st.QH*state.prices.QH,ii:st.II*state.prices.II,bz:st.BZ*state.prices.BZ,total:total(st)}))}
function render(){renderMarket();renderRewards();renderStudents();renderActionSelectors();renderHistory();renderLog();drawGraph();save()}
function renderMarket(){const body=document.querySelector("#marketTable tbody");body.innerHTML="";Object.keys(companies).forEach(t=>{const tr=document.createElement("tr");tr.innerHTML=`<td>${companies[t]}</td><td><b>${t}</b></td><td>${state.prices[t]}</td><td class="${cls(state.lastChange[t])}">${sig(state.lastChange[t])}</td><td>${state.sharesAvailable[t]}</td>`;body.appendChild(tr)});document.getElementById("lessonSelect").value=state.lesson;const c=state.drawnCounts[state.lesson]||0;document.getElementById("tradeReminder").textContent=c%2===0&&c>0?"Trading round reminder: students may BUY, SELL or HOLD.":"Draw two cards, then offer a trading round."}
function renderRewards(){const body=document.querySelector("#rewardsTable tbody");body.innerHTML="";state.rewards.forEach((p,i)=>{const tr=document.createElement("tr");tr.innerHTML=`<td>Prize Box ${i+1}</td><td>${p} tickets</td><td><input type="number" min="0" value="${p}" data-reward="${i}"></td>`;body.appendChild(tr)});body.querySelectorAll("input").forEach(inp=>inp.onchange=e=>{state.rewards[+e.target.dataset.reward]=+e.target.value||0;addLog(`Prize Box ${+e.target.dataset.reward+1} price set to ${e.target.value}`);render()})}
function renderStudents(){const body=document.querySelector("#studentsTable tbody");body.innerHTML="";state.students.forEach((st,i)=>{const tr=document.createElement("tr");tr.innerHTML=`<td>${st.name}</td><td>${st.cash}</td><td>${st.QH}</td><td>${st.II}</td><td>${st.BZ}</td><td>${st.bank.reduce((a,d)=>a+d.value,0)}</td><td><b>${total(st)}</b></td><td><button data-del="${i}" class="danger">Remove</button></td>`;body.appendChild(tr)});body.querySelectorAll("button[data-del]").forEach(b=>b.onclick=()=>{if(confirm("Remove this student?")){state.students.splice(+b.dataset.del,1);render()}})}
function renderActionSelectors(){["actionStudent","graphStudent"].forEach(id=>{const s=document.getElementById(id),v=s.value;s.innerHTML="";state.students.forEach((st,i)=>{const o=document.createElement("option");o.value=i;o.textContent=st.name;s.appendChild(o)});if(v)s.value=v});const type=document.getElementById("actionType").value,t=document.getElementById("actionTarget");t.innerHTML="";let opts=[];if(type==="buy"||type==="sell")opts=Object.keys(companies).map(k=>[k,`${k} - ${companies[k]}`]);else if(type==="spend")opts=state.rewards.map((p,i)=>[i,`Prize Box ${i+1} (${p} tickets)`]);else if(type==="deposit")opts=[[1,"1 lesson (+10%)"],[2,"2 lessons (+20%)"],[3,"3 lessons (+30%)"]];else if(type==="withdraw")opts=[[0,"Withdraw oldest deposit"]];else opts=[["cash","Cash adjustment"]];opts.forEach(([v,txt])=>{const o=document.createElement("option");o.value=v;o.textContent=txt;t.appendChild(o)})}
function renderHistory(){const body=document.querySelector("#historyTable tbody");body.innerHTML="";state.history.slice(-120).reverse().forEach(h=>{const tr=document.createElement("tr");tr.innerHTML=`<td>${h.round}</td><td>${h.name}</td><td>${h.cash}</td><td>${h.bank}</td><td>${h.qh}</td><td>${h.ii}</td><td>${h.bz}</td><td><b>${h.total}</b></td>`;body.appendChild(tr)})}
function renderLog(){document.getElementById("logBox").value=state.log.join("\n")}
document.getElementById("addStudentBtn").onclick=()=>{const name=document.getElementById("studentName").value.trim();const cash=+document.getElementById("studentCash").value;if(!name||Number.isNaN(cash))return alert("Enter a name and starting tickets.");state.students.push({name,cash,QH:0,II:0,BZ:0,bank:[]});addLog(`Added ${name} with ${cash} tickets.`);document.getElementById("studentName").value="";document.getElementById("studentCash").value="";render()}
document.getElementById("lessonSelect").onchange=e=>{state.lesson=+e.target.value;render()};document.getElementById("actionType").onchange=renderActionSelectors;
document.getElementById("shuffleDeckBtn").onclick=()=>{state.deckOrder[state.lesson]=shuffle([...Array(decks[state.lesson].length).keys()]);state.drawnCounts[state.lesson]=0;addLog(`Shuffled Lesson ${state.lesson} deck.`);render()}
document.getElementById("drawCardBtn").onclick=()=>{const l=state.lesson,c=state.drawnCounts[l]||0;if(c>=decks[l].length)return alert("All cards in this lesson have been drawn.");const idx=state.deckOrder[l][c],card=decks[l][idx],before={prices:{...state.prices},lastChange:{...state.lastChange}};Object.keys(card.impact).forEach(t=>{state.lastChange[t]=card.impact[t];state.prices[t]=Math.max(1,state.prices[t]+card.impact[t])});state.drawnCounts[l]=c+1;state.drawnCards.push({lesson:l,cardIndex:idx,before});document.getElementById("drawnCard").innerHTML=`<span class="event-title">${card.title}</span>${card.text}<div class="impact">${Object.keys(card.impact).map(t=>`<span class="${cls(card.impact[t])}">${t} ${sig(card.impact[t])}</span>`).join("")}</div>`;addLog(`Lesson ${l} card drawn: ${card.title}.`);snapshot(`L${l} Card ${c+1}`);render()}
document.getElementById("undoCardBtn").onclick=()=>{const last=state.drawnCards.pop();if(!last)return;state.prices=last.before.prices;state.lastChange=last.before.lastChange;state.drawnCounts[last.lesson]=Math.max(0,(state.drawnCounts[last.lesson]||1)-1);addLog("Undid last market card.");render()}
document.getElementById("applyActionBtn").onclick=()=>{const idx=+document.getElementById("actionStudent").value,st=state.students[idx];if(!st)return alert("Select a student.");const type=document.getElementById("actionType").value,target=document.getElementById("actionTarget").value,amt=+document.getElementById("actionAmount").value;if(Number.isNaN(amt))return alert("Enter an amount.");if(type==="buy"){const cost=state.prices[target]*amt;if(amt<1||state.sharesAvailable[target]<amt)return alert("Not enough shares available.");if(st.cash<cost)return alert("Student does not have enough cash.");st.cash-=cost;st[target]+=amt;state.sharesAvailable[target]-=amt;addLog(`${st.name} bought ${amt} ${target} for ${cost}.`)}else if(type==="sell"){if(amt<1||st[target]<amt)return alert("Student does not own enough shares.");const val=state.prices[target]*amt;st[target]-=amt;st.cash+=val;state.sharesAvailable[target]+=amt;addLog(`${st.name} sold ${amt} ${target} for ${val}.`)}else if(type==="spend"){const price=state.rewards[+target]*amt;if(st.cash<price)return alert("Student does not have enough cash.");st.cash-=price;addLog(`${st.name} bought ${amt} x Prize Box ${+target+1} for ${price}.`)}else if(type==="deposit"){if(amt<10||amt%10!==0)return alert("Bank deposits must be in 10-ticket lots.");if(st.cash<amt)return alert("Student does not have enough cash.");const term=+target,rate={1:.10,2:.20,3:.30}[term],value=Math.round(amt*(1+rate));st.cash-=amt;st.bank.push({amount:amt,term,value,lesson:state.lesson});addLog(`${st.name} deposited ${amt} for ${term} lesson(s), return ${value}.`)}else if(type==="withdraw"){if(st.bank.length===0)return alert("No deposits recorded.");const dep=st.bank.shift();st.cash+=dep.value;addLog(`${st.name} withdrew bank deposit worth ${dep.value}.`)}else{st.cash+=amt;addLog(`${st.name} cash adjusted by ${amt}.`)}snapshot("Action");render()}
function drawGraph(){const canvas=document.getElementById("graphCanvas"),ctx=canvas.getContext("2d");ctx.clearRect(0,0,canvas.width,canvas.height);const idx=+document.getElementById("graphStudent").value,st=state.students[idx];if(!st)return;const data=state.history.filter(h=>h.name===st.name).slice(-30);ctx.fillStyle="#08234a";ctx.font="18px Arial";ctx.fillText(`${st.name} Portfolio Value`,20,28);ctx.strokeStyle="#c8d3df";ctx.lineWidth=1;for(let i=0;i<6;i++){const y=320-i*48;ctx.beginPath();ctx.moveTo(45,y);ctx.lineTo(700,y);ctx.stroke()}if(data.length<2)return;const max=Math.max(...data.map(d=>d.total),10);ctx.strokeStyle="#0c5ca8";ctx.lineWidth=3;ctx.beginPath();data.forEach((d,i)=>{const x=55+i*(630/Math.max(1,data.length-1)),y=320-(d.total/max)*260;if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)});ctx.stroke();ctx.fillStyle="#132238";ctx.font="12px Arial";ctx.fillText("0",20,322);ctx.fillText(`${max}`,12,62)}
document.getElementById("graphStudent").onchange=drawGraph;
document.getElementById("exportBtn").onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="investor-challenge-backup.json";a.click()}
document.getElementById("importFile").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state=JSON.parse(r.result);addLog("Imported backup.");render()}catch(err){alert("Invalid backup file.")}};r.readAsText(f)}
document.getElementById("resetBtn").onclick=()=>{if(confirm("Reset all data? Export a backup first if needed.")){localStorage.removeItem("investorChallengeState");state=loadState();render()}}
render();
