const KEY="investorChallenge.v1";
const masterDecks={
1:[["Strong Consumer Spending","Families are spending more money in shops.",{QH:1,II:0,BZ:0}],["Positive Economic News","Businesses are optimistic about the economy.",{QH:1,II:1,BZ:1}],["New Infrastructure Contract","A major construction project has been announced.",{QH:0,II:2,BZ:0}],["Technology Award","A new innovation has attracted attention.",{QH:0,II:0,BZ:2}],["Rising Business Costs","Higher operating costs affect many companies.",{QH:-1,II:-1,BZ:-1}],["Online Shopping Boom","Consumer spending continues to grow.",{QH:1,II:0,BZ:1}],["Investor Confidence Rises","Investors are willing to take more risks.",{QH:1,II:1,BZ:2}],["Supply Chain Delays","Shipping delays affect some businesses.",{QH:-1,II:-2,BZ:0}],["New Government Investment","Government spending supports business growth.",{QH:1,II:2,BZ:1}],["Strong Market Finish","The market closes the lesson positively.",{QH:1,II:1,BZ:1}]],
2:[["Mixed Trading Day","Some investors take profits while others continue buying.",{QH:1,II:0,BZ:1}],["Strong Employment Data","The economy appears healthy.",{QH:1,II:1,BZ:2}],["Overseas Markets Fall","International markets experience losses.",{QH:-1,II:-1,BZ:-2}],["Investor Uncertainty","Rumours create concern among investors.",{QH:-1,II:-2,BZ:-2}],["Market Crash","Breaking news shocks investors. Panic selling begins across the market.",{QH:-3,II:-4,BZ:-6}],["Market Panic Continues","Many investors continue selling their shares.",{QH:-1,II:-2,BZ:-3}],["Bargain Hunters Enter","Some investors begin buying cheap shares.",{QH:1,II:1,BZ:2}],["Government Support Package","Support measures help businesses and boost confidence.",{QH:2,II:2,BZ:2}],["Investor Confidence Returns","The market begins recovering.",{QH:1,II:2,BZ:3}],["Recovery Rally","Investors return to the market as prices rise strongly.",{QH:2,II:2,BZ:4}]],
3:[["Consumer Confidence Returns","Shoppers are spending again.",{QH:2,II:1,BZ:1}],["Stable Trading Day","Investors remain cautious but optimistic.",{QH:1,II:1,BZ:1}],["Major Infrastructure Project","Government announces new transport funding.",{QH:0,II:3,BZ:1}],["Technology Product Launch","A new product receives positive reviews.",{QH:0,II:0,BZ:3}],["Rising Interest Rates","Borrowing becomes more expensive.",{QH:-1,II:-1,BZ:-2}],["Strong Company Earnings","Businesses report better-than-expected profits.",{QH:1,II:2,BZ:2}],["Supply Problems Return","Some industries experience delays.",{QH:-1,II:-2,BZ:-1}],["Investor Optimism","Many investors expect future growth.",{QH:1,II:1,BZ:2}],["Market Rally","Investors buy shares across the market.",{QH:2,II:2,BZ:2}],["End-of-Simulation Surge","Strong buying pushes prices higher before trading closes.",{QH:1,II:2,BZ:3}]]
};
function card(a){return{title:a[0],text:a[1],effects:a[2]}}
function clone(x){return JSON.parse(JSON.stringify(x))}
function fresh(){return{lesson:1,cardIndex:0,companies:{QH:{name:"Quokka Holdings",price:3,previous:3,available:40},II:{name:"Ironbark Industries",price:5,previous:5,available:25},BZ:{name:"Blue Zenith Technologies",price:10,previous:10,available:15}},rewards:[1,2,3,4,5,6].map((n,i)=>({id:n,name:"Prize Box "+n,price:[8,10,12,15,20,30][i]})),students:[],log:[],decks:{1:masterDecks[1].map(card),2:masterDecks[2].map(card),3:masterDecks[3].map(card)}}}
let state=localStorage.getItem(KEY)?JSON.parse(localStorage.getItem(KEY)):fresh();
function save(){localStorage.setItem(KEY,JSON.stringify(state));document.getElementById("saveStatus").textContent="Saved "+new Date().toLocaleTimeString()}
function addLog(s){state.log.unshift("["+new Date().toLocaleTimeString()+"] "+s);save();render()}
function bankValue(s){return (s.deposits||[]).reduce((a,d)=>a+d.maturityValue,0)}
function val(s,t){return (s.shares[t]||0)*state.companies[t].price}
function portfolio(s){return Math.round(s.cash+bankValue(s)+val(s,"QH")+val(s,"II")+val(s,"BZ"))}
function snapshot(s,label){s.history=s.history||[];s.history.push({label,lesson:state.lesson,card:state.cardIndex,value:portfolio(s),cash:s.cash,bank:bankValue(s),time:new Date().toISOString()})}
function snapshotAll(){state.students.forEach(s=>snapshot(s,"L"+state.lesson+" C"+state.cardIndex));addLog("Saved snapshot for all students.")}
function render(){marketRows();rewardRows();studentRows();selects();status();leaders();renderActivityFields(false);drawChart();document.getElementById("log").textContent=state.log.join("\n");save()}
function marketRows(){document.getElementById("marketRows").innerHTML=Object.entries(state.companies).map(([t,c])=>{let ch=c.price-c.previous,cls=ch>0?"pos":ch<0?"neg":"zero";return `<tr><td><b>${c.name}</b> (${t})</td><td>${c.price}</td><td class="${cls}">${ch>0?"+":""}${ch}</td><td>${c.available}</td></tr>`}).join("")}
function rewardRows(){document.getElementById("rewardRows").innerHTML=state.rewards.map(r=>`<tr><td>${r.name}</td><td>${r.price}</td><td><input type="number" value="${r.price}" onchange="setReward(${r.id},this.value)"></td></tr>`).join("")}
function studentRows(){document.getElementById("studentRows").innerHTML=state.students.map(s=>`<tr><td><b>${s.name}</b></td><td>${s.cash}</td><td>${s.shares.QH}</td><td>${s.shares.II}</td><td>${s.shares.BZ}</td><td>${bankValue(s)}</td><td><b>${portfolio(s)}</b></td><td><button onclick="removeStudent('${s.id}')">Remove</button></td></tr>`).join("")}
function selects(){["activeStudent","chartStudent"].forEach(id=>{let el=document.getElementById(id);if(!el)return;let v=el.value;el.innerHTML=state.students.map(s=>`<option value="${s.id}">${s.name}</option>`).join("");if(state.students.some(s=>s.id===v))el.value=v});summary()}
function status(){document.getElementById("statusText").textContent=`Lesson ${state.lesson} • Card ${state.cardIndex} of 10`;let can=state.cardIndex>0&&state.cardIndex%2===0;let r=document.getElementById("tradeReminder");r.textContent=can?"Trading Round: students may BUY, SELL or HOLD.":"Wait for next card before trading.";r.className="reminder"+(can?" trade":"")}
function leaders(){let arr=[...state.students].sort((a,b)=>portfolio(b)-portfolio(a));document.getElementById("leaderRows").innerHTML=arr.map((s,i)=>`<tr><td>${i+1}</td><td>${s.name}</td><td><b>${portfolio(s)}</b></td><td>${note(s)}</td></tr>`).join("")}
function note(s){let shares=val(s,"QH")+val(s,"II")+val(s,"BZ"),bank=bankValue(s);if(shares>s.cash&&shares>bank)return"Mostly investing";if(bank>s.cash&&bank>shares)return"Mostly saving";if((s.spending||[]).length>1)return"Spending active";return"Mixed / developing"}
function addStudent(){let name=document.getElementById("studentName").value.trim(),cash=Number(document.getElementById("studentCash").value);if(!name||isNaN(cash))return alert("Enter name and starting tickets.");let s={id:String(Date.now()+Math.random()),name,cash:Math.round(cash),shares:{QH:0,II:0,BZ:0},deposits:[],spending:[],history:[]};state.students.push(s);snapshot(s,"Start");document.getElementById("studentName").value="";document.getElementById("studentCash").value="";addLog(`Added ${name} with ${cash} tickets.`)}
function removeStudent(id){let s=state.students.find(x=>x.id===id);if(s&&confirm("Remove "+s.name+"?")){state.students=state.students.filter(x=>x.id!==id);addLog("Removed "+s.name)}}
function active(){return state.students.find(s=>s.id===document.getElementById("activeStudent").value)}
function renderActivityFields(doSummary=true){let box=document.getElementById("activityFields");if(!box)return;let type=document.getElementById("activityType").value;if(type==="buy"||type==="sell")box.innerHTML=`<select id="ticker"><option>QH</option><option>II</option><option>BZ</option></select><input id="qty" type="number" min="1" placeholder="Shares">`;else if(type==="deposit")box.innerHTML=`<input id="depAmount" type="number" min="10" step="10" placeholder="Amount"><select id="depTerm"><option value="1">1 lesson +10%</option><option value="2">2 lessons +20%</option><option value="3">3 lessons +30%</option></select>`;else box.innerHTML=`<select id="reward">${state.rewards.map(r=>`<option value="${r.id}">${r.name} - ${r.price} tickets</option>`).join("")}</select>`;if(doSummary)summary()}
function submitActivity(){let s=active();if(!s)return alert("Select student.");let type=document.getElementById("activityType").value;if(type==="buy")buy(s);if(type==="sell")sell(s);if(type==="deposit")deposit(s);if(type==="spend")spend(s)}
function buy(s){let t=document.getElementById("ticker").value,q=Number(document.getElementById("qty").value),c=state.companies[t],cost=q*c.price;if(!q||q<1)return;if(c.available<q)return alert("Not enough shares available.");if(s.cash<cost)return alert("Not enough cash.");s.cash-=cost;s.shares[t]+=q;c.available-=q;snapshot(s,"Buy "+q+" "+t);addLog(`${s.name} bought ${q} ${t} for ${cost}.`)}
function sell(s){let t=document.getElementById("ticker").value,q=Number(document.getElementById("qty").value),c=state.companies[t];if(!q||q<1)return;if(s.shares[t]<q)return alert("Student does not own enough shares.");let money=q*c.price;s.shares[t]-=q;s.cash+=money;c.available+=q;snapshot(s,"Sell "+q+" "+t);addLog(`${s.name} sold ${q} ${t} for ${money}.`)}
function deposit(s){let amount=Number(document.getElementById("depAmount").value),term=Number(document.getElementById("depTerm").value);if(!amount||amount<10||amount%10!==0)return alert("Deposits must be at least 10 and in 10-ticket lots.");if(s.cash<amount)return alert("Not enough cash.");let maturity=Math.round(amount*(1+term*.1));s.cash-=amount;s.deposits.push({amount,term,lessonsRemaining:term,maturityValue:maturity});snapshot(s,"Deposit "+amount);addLog(`${s.name} deposited ${amount} for ${term} lesson(s), maturity ${maturity}.`)}
function spend(s){let id=Number(document.getElementById("reward").value),r=state.rewards.find(x=>x.id===id);if(s.cash<r.price)return alert("Not enough cash.");s.cash-=r.price;s.spending.push({lesson:state.lesson,item:r.name,cost:r.price,time:new Date().toISOString()});snapshot(s,"Spend "+r.name);addLog(`${s.name} bought ${r.name} for ${r.price}.`)}
function summary(){let s=active(),el=document.getElementById("studentSummary");if(!el)return;if(!s){el.innerHTML="No student selected.";return}el.innerHTML=`<div><b>Cash</b><br>${s.cash}</div><div><b>Portfolio</b><br>${portfolio(s)}</div><div><b>QH</b><br>${s.shares.QH} = ${val(s,"QH")}</div><div><b>II</b><br>${s.shares.II} = ${val(s,"II")}</div><div><b>BZ</b><br>${s.shares.BZ} = ${val(s,"BZ")}</div><div><b>Bank</b><br>${bankValue(s)}</div>`}
function selectLesson(){state.lesson=Number(document.getElementById("lessonSelect").value);state.cardIndex=0;addLog("Selected Lesson "+state.lesson)}
function resetDeck(){state.decks[state.lesson]=masterDecks[state.lesson].map(card);state.cardIndex=0;addLog("Reset Lesson "+state.lesson+" deck.")}
function shuffle(a){for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function shuffleDeck(){if(state.lesson===2){let d=masterDecks[2].map(card);state.decks[2]=[...shuffle(d.slice(0,4)),d[4],...shuffle(d.slice(5))]}else state.decks[state.lesson]=shuffle(masterDecks[state.lesson].map(card));state.cardIndex=0;addLog("Shuffled Lesson "+state.lesson+" deck.")}
function drawCard(){let d=state.decks[state.lesson];if(state.cardIndex>=d.length)return alert("No cards left.");let c=d[state.cardIndex++];Object.entries(c.effects).forEach(([t,e])=>{let co=state.companies[t];co.previous=co.price;co.price=Math.max(1,co.price+e)});document.getElementById("currentCard").innerHTML=`<span class="badge">Lesson ${state.lesson} • Card ${state.cardIndex}</span><h2>${c.title}</h2><p>${c.text}</p><h3>Impact on share prices</h3>${Object.entries(c.effects).map(([t,e])=>`<div class="effect ${e>0?"pos":e<0?"neg":"zero"}">${t}: ${e>0?"+":""}${e}</div>`).join("")}`;state.students.forEach(s=>snapshot(s,`L${state.lesson} C${state.cardIndex}`));addLog(`Drew card: ${c.title}.`)}
function setReward(id,v){let r=state.rewards.find(x=>x.id===id);r.price=Number(v);addLog(`Updated ${r.name} to ${r.price}.`)}
function applyInflation(){state.rewards.forEach(r=>r.price+=2);addLog("Applied inflation +2 to all Prize Boxes.")}
function editMarket(){document.getElementById("marketEditor").innerHTML=Object.entries(state.companies).map(([t,c])=>`<p><b>${c.name} (${t})</b> Price <input id="p_${t}" type="number" value="${c.price}"> Available <input id="a_${t}" type="number" value="${c.available}"></p>`).join("");document.getElementById("modal").classList.remove("hidden")}
function saveMarketEdit(){Object.entries(state.companies).forEach(([t,c])=>{c.previous=c.price;c.price=Number(document.getElementById("p_"+t).value);c.available=Number(document.getElementById("a_"+t).value)});closeModal();addLog("Edited market.")}
function closeModal(){document.getElementById("modal").classList.add("hidden")}
function exportJSON(){download("investor-challenge-backup.json",JSON.stringify(state,null,2),"application/json")}
function importJSON(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{state=JSON.parse(r.result);save();render();alert("Imported backup.")};r.readAsText(f)}
function exportCSV(){let rows=[["Name","Cash","QH","II","BZ","Bank","Portfolio","Purchases"]];state.students.forEach(s=>rows.push([s.name,s.cash,s.shares.QH,s.shares.II,s.shares.BZ,bankValue(s),portfolio(s),(s.spending||[]).length]));download("investor-challenge-students.csv",rows.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(",")).join("\n"),"text/csv")}
function download(n,t,type){let b=new Blob([t],{type}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=n;a.click();URL.revokeObjectURL(a.href)}
function resetAll(){if(confirm("Reset all data?")){state=fresh();save();render()}}
function drawChart(){let canvas=document.getElementById("chart");if(!canvas)return;let ctx=canvas.getContext("2d");ctx.clearRect(0,0,canvas.width,canvas.height);let id=document.getElementById("chartStudent")?.value,s=state.students.find(x=>x.id===id)||state.students[0];if(!s||!s.history?.length){ctx.fillText("No portfolio history yet.",30,40);return}let data=s.history.slice(-20),vals=data.map(d=>d.value),max=Math.max(...vals,10),min=Math.min(...vals,0),pad=40,w=canvas.width-pad*2,h=canvas.height-pad*2;ctx.strokeStyle="#d6dfec";for(let i=0;i<5;i++){let y=pad+h/4*i;ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(canvas.width-pad,y);ctx.stroke()}ctx.strokeStyle="#0b5cad";ctx.lineWidth=3;ctx.beginPath();data.forEach((d,i)=>{let x=pad+w/(Math.max(data.length-1,1))*i,y=pad+h-((d.value-min)/(Math.max(max-min,1)))*h;if(i)ctx.lineTo(x,y);else ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle="#06214a";ctx.font="18px Arial";ctx.fillText(`${s.name}: Portfolio value over time`,pad,24);ctx.font="12px Arial";data.forEach((d,i)=>{let x=pad+w/(Math.max(data.length-1,1))*i,y=pad+h-((d.value-min)/(Math.max(max-min,1)))*h;ctx.beginPath();ctx.arc(x,y,4,0,Math.PI*2);ctx.fill();ctx.fillText(d.value,x-8,y-10)})}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.getElementById(b.dataset.tab).classList.add("active");drawChart()});
render();
